# Lecture Notes 

### a quick intro to numpy instert 

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.insert.html

inputing without and axis flattens the matrix into an array

In [149]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [150]:
a = np.insert(a, 1, 5)
a

array([1, 5, 1, 2, 2, 3, 3])

In [254]:
b = np.array([[1, 1], [2, 2], [3, 3]])
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [255]:
b = np.insert(b, 1, 5, axis = 0) # 1 is y axis ( add a column)  0 is x axis ( add a row)
b

array([[1, 1],
       [5, 5],
       [2, 2],
       [3, 3]])

Input rows i or coloumns [j]

In [241]:
c = np.array([[1, 1], [2, 2], [3, 3]])
# Adjust the x in  np.insert(c, x ... to controld j (column) insertion point
# [x] is row
# x is column ... when axis is 1 
np.insert(c, 0, [4, 4, 4], axis=1)

array([[4, 1, 1],
       [4, 2, 2],
       [4, 3, 3]])

In [190]:
c = np.array([[1, 1], [2, 2], [3, 3]])
c
np.insert(c, [2], [[4],[4],[4]], axis=1)

array([[1, 1, 4],
       [2, 2, 4],
       [3, 3, 4]])

In [137]:
d = np.array([[1, 1], [2, 2], [3, 3]])
d = d.flatten()
d

array([1, 1, 2, 2, 3, 3])

In [136]:
np.insert(d, slice(2, 4), [5, 6])

array([1, 1, 5, 2, 6, 2, 3, 3])

In [ ]:
np.insert(d, [2, 1, 0], [7.13, True, False]) # type casting # note the rounding of 7.13

parsing numpy arrays 

In [259]:
d = np.array([[1, 1, 6], [2, 2, 6], [3, 3, 7]])                
d[:,:]      # Display all rows and columns
d[0:3,0:2]  # Display all rows but only 0th and 1st column i.e (0, 1) exluding 2

array([[1, 1],
       [2, 2],
       [3, 3]])

# Chapter 2.2 Notes: The Idea of Elimination

elimination produces an upper triangular system - this is the goal

Note: you wont find a library in python for 'elimination matices' because they are only used for teaching how matix act of rows... that said, lets make a function that creates our elimination matix! 

In [394]:
A = np.array([[2, 4, -2],[4,9, -3], [-2, -3, 7]])
A

array([[ 2,  4, -2],
       [ 4,  9, -3],
       [-2, -3,  7]])

In [398]:
def elimination_matrix_creator(A): 
    for row_num, i in enumerate (A):
        for k in range(len(A[row_num:, row_num])):
            j = 1
            try:
                A[row_num + j] = A[row_num + j] - (A[row_num] * (A[row_num +j, row_num] / A[row_num, row_num]))
                j += k
                A[row_num + j] = A[row_num + j] - (A[row_num] * (A[row_num +j, row_num] / A[row_num, row_num]))
            except: 
                pass
    return A
                
E = elimination_matrix(A)
E

array([[ 2,  4, -2],
       [ 0,  1,  1],
       [ 0,  0,  4]])

array([[ 4, 16,  4],
       [ 0,  1,  1],
       [ 0,  0, 16]])

In [378]:
from numpy import array
from scipy.linalg import lu

pl, u = lu(A, permute_l=True) # fun fact you can start at the second rows pivot by adding (A, -1)
                                     # ... read on for a definition of 'pivot'
u

array([[ 7.        , -2.        ,  5.        ],
       [ 0.        ,  4.        ,  3.        ],
       [ 0.        ,  0.        , -1.71428571]])

 ### Breakdown of Eleimiation 

## Three Equations in Three Unknows

## Elimination from A to U 

# Elimitation Using Matrices

## Matrices tiem Vectors and ${A}{x} = {b}$

## The Matrix From of One Elimiation Strep

## Matrix Multiplication

## The Matrix ${p}_{ij}$ for a Row Exchange

## The Augmented Matrix